spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cardb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  application:
    name: CarStationService
  profiles:
    active: dev
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cab-realm
          jwk-set-uri: http://localhost:8080/realms/cab-realm/protocol/openid-connect/certs
server:
  port: 4560

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    org.springframework.security: DEBUG

keycloak:
  clientId: cab-aggregator