spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/carDB
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: CarStationService
server:
  port: 4567