spring:
  datasource:
    url: jdbc:postgresql://my_postgres:5432/driverdb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: DriverService
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password
server:
  port: 4567

rabbitmq:
  queues:
    request: request.queue
    response: response.queue

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true

service:
  car-service:
    name: CarStationService
    path: /api/v1/cars