spring:
  datasource:
    url: jdbc:postgresql://my_postgres:5432/passengerdb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: none
  web:
    resources:
      static-locations: classpath:/static/
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: PassengerService
server:
  port: 4566

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true