spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/passengerDB
  jpa:
    hibernate:
      ddl-auto: none
  web:
    resources:
      static-locations: classpath:/static/
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  application:
    name: PassengerService
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/cab-realm
          jwk-set-uri: http://keycloak:8080/realms/cab-realm/protocol/openid-connect/certs
server:
  port: 4566

eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true


keycloak:
  clientId: cab-aggregator